# Netlify Build Settings
[build]
  command = "npm run build"
  publish = "build"
  functions = "api"

# CORRECTED rewrite rule for the API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Fallback rewrite rule for the React App (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200